"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[❯❯](peach)"
palette = "catppuccin_mocha"

# Basics:
[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$ssh_symbol$hostname]($style) in '
style = "bold yellow"
trim_at = "."
disabled = false

[character]
success_symbol = "[[󰄛](bold green) ❯](peach)"
error_symbol = "[[󰄛](bold red) ❯](peach)"

[directory]
before_repo_root_style = "lavender"
repo_root_style = "bold red"
style = "bold sky"
home_symbol = '~'
format = "[$path]($style)[$read_only]($read_only_style) "
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
read_only = " 󰌾"
truncation_symbol = ''
truncation_length = 4
truncate_to_repo = true
use_logical_path = false

[cmd_duration]
min_time = 10_000
format = '\[[⏱ $duration]($style)\]'
style = 'yellow'

################################################################################
## GIT
################################################################################
[git_branch]
format = 'on [$symbol$branch]($style)'
symbol = " "
style = "bold green"

[git_status]
conflicted = "󰞇 "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕ ⇡${ahead_count} ⇣${behind_count} "
untracked = "${count} "
stashed = " "
modified = " ${count} "
staged = "${count} "
renamed = "»${count} "
deleted = "✘${count} "
style = "peach"
format = '\[$all_status$ahead_behind\]'

[git_commit]
commit_hash_length = 8
style = "bold teal"
tag_symbol = ' '
disabled = false


################################################################################
## EXTRAS
################################################################################
[docker_context]
disabled = false
symbol = " "
style = "blue bold"
format = "via [$symbol$context]($style) "
only_with_files = true

[aws]
disabled = true

# Palattes:
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
